### ISSUE TITLE
[Bug] Running and closed events can update event dates

### ISSUE THREAD

**Issue by AquaXV** [CodeMyst/VoteMyst#118]
## Description
An event can have its dates updated at any point in time; when an event is finished (voting closed) you can update it to be active again, or even hidden.

## Reproduction
Create an event, update dates.

## Expected Behaviour
That at most you can only update the most recently passed date; If an event has just started you can hide it, if voting started that you can extend submission period, and when an event has finished that you can stretch the voting period.

**Comment by YilianSource** [comment]
> That at most you can only update the most recently passed date;

Don't you mean that you can update the _next upcoming_ date? Or do we allow voting to be re-opened that way?

**Comment by AquaXV** [comment]
Hmm.. Perhaps the first 2 can only be changed before the date passes and the last 2 after the fact (with at most 1 date prior; so after voting closes you can't reopen submissions)

**Comment by yiliansource** [comment]
@AquaXV, so just that I'm getting this correctly:

When previously in a `Hidden` state, it can go into any state.
When previously in a `Revealed` state, it can go into any state **except** `Hidden`.
When previously in a `Ongoing` state, it can only go into `Ongoing`, `Voting` or `Closed`.
When previously in a `Voting` state, it can only go into `Voting` or `Closed`.
When previously in a `Closed` state, it can only stay `Closed`.

**Comment by AquaXV** [comment]
That sounds right to me.
