### ISSUE TITLE
[Proposal] Forward reports to hosts of event as well

### ISSUE THREAD

**Issue by AquaXV** [CodeMyst/VoteMyst#126]
## Description
Site admins should not dictate content for events hosted by users; let the event hosts handle grey area. Site moderators/admins can deal with TOS breaking. Hosts should deal with grey area entries.

## Suggested Implementations
Page with reports for Hosts of Events.

**Comment by yiliansource** [comment]
I was actually thinking of that already. I'll probably remove the `/reports` endpoint and make an `/event/{id}/reports` tab instead.
