### ISSUE TITLE
[Proposal] Include a X on entries so hosts/moderators can delete entries

### ISSUE THREAD

**Issue by AquaXV** [CodeMyst/VoteMyst#130]
## Description
Right now it is not possible to delete entries without them being reported.

## Suggested Implementations
Include an X to the entries for hosts/site staff to delete said entry without needing a report.

**Comment by yiliansource** [comment]
This would be covered in #122, is that fine aswell?

**Comment by AquaXV** [comment]
Yes! I missed that issue haha.
