### ISSUE TITLE
[Proposal] Changes to visuals of event overview on mobile

### ISSUE THREAD

**Issue by AquaXV** [CodeMyst/VoteMyst#132]
## Description
On the event overview page the timer spans 2 lines, this should probably become 1, and it would be nice for mobile users to be able to click anywhere on the card to open the event.
![Screenshot_20200622-085441](https://user-images.githubusercontent.com/1627290/85257606-67d68f80-b466-11ea-8c24-56fdd501c29e.jpg)

## Suggested Implementations
Put submissions on single line and make entire event card clickable (for at least mobile)

**Comment by yiliansource** [comment]
Putting the timer on a single line is definitely possible, since it's just a CSS query, but I wouldn't know how to make the entire event card clickable for mobile only.

**Comment by AquaXV** [comment]
Can make the entire card clickable for PC and mobile
