### ISSUE TITLE
[Proposal] Feature current events on the homepage

### ISSUE THREAD

**Issue by yiliansource** [CodeMyst/VoteMyst#136]
## Description

Currently the homepage is a bit empty and boring.

![image](https://user-images.githubusercontent.com/41469451/87295486-8da30180-c505-11ea-97c9-b1e09124c3a5.png)

## Suggested Implementations

Similarly to the initial version, the homepage could feature a specific event that is currently held. Another idea would be to feature freshly uploaded entries.

**Comment by CodeMyst** [comment]
id say do it like itch, show the most recent upcoming and ongoing events.
