### ISSUE TITLE
[Bug] Contributing link on readme is broken.

### ISSUE THREAD

**Issue by haaarshsingh** [CodeMyst/VoteMyst#148]
## Description

Contributing link on `readme` is broken.

## Reproduction

Fix the link.

## Expected Behaviour

Link me to the actual page.

**Comment by yiliansource** [comment]
That's only on the `master` branch. It's fixed in the `development` version: https://github.com/CodeMyst/VoteMyst/tree/development

We're (hopefully) going to finish the last 2 issues soon, enter version 1.0 and merge into master together with the public release.
