### ISSUE TITLE
add more places to see the old events

### ISSUE THREAD

**Issue by CodeMyst** [CodeMyst/VoteMyst#63]
currently only a single link exists to view old events, on the homepage
![image](https://user-images.githubusercontent.com/7966628/81501272-cfca7f80-92d7-11ea-80c1-aac0f58e427b.png)

**Comment by CodeMyst** [comment]
maybe a link in the navigation? call it archive maybe?

**Comment by yiliansource** [comment]
But you can already see these in the regular event overview, the "old events" link isn't a separate page, it shows all the events, no matter if upcoming, ongoing or expired.

**Comment by CodeMyst** [comment]
ah i didn't know that, that is completely fine. no need for more links then
